name: coresystem
description: 2M project.

publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bot_toast: ^4.0.1
  clipboard: any
  connectivity: ^3.0.4
  cupertino_icons: ^1.0.3
  data_connection_checker: any
  dotted_border: ^2.0.0
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  http:
  image_cropper: any
  image_picker: any
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  shared_preferences: ^2.0.5
  lottie: ^1.2.1
  flutter_automation: ^2.0.0
  package_info_plus: ^1.4.2
  google_ml_kit: ^0.11.0
  exif: ^3.0.1
  image: ^3.1.1
  hive: ^2.2.2
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/Assets/IconApp/
    - lib/Assets/Images/
    - lib/Assets/Svg/
    - lib/Assets/Json/

flutter_intl:
  enabled: true
