name: coresystem
description: 2M project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bot_toast: ^4.0.1
  clipboard: any
  cupertino_icons: ^1.0.3
  dotted_border: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  http:
  image_cropper: 1.5.1
  image_picker: any
  shared_preferences: ^2.0.5
  lottie: ^1.2.1
  flutter_automation: ^2.0.0
  package_info_plus: ^1.4.2
  google_ml_kit: ^0.11.0
  exif: ^3.0.1
  image: ^3.1.1
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  uuid: ^3.0.6
  auto_size_text: ^3.0.0
  math_expressions: ^2.0.1
  get: ^4.6.5
  flutter_ios_calculator: ^0.1.0
  syncfusion_flutter_datepicker: 20.1.50
  date_picker_timeline: ^1.2.3
  clickable_list_wheel_view: 0.1.0
  flutter_image_compress: ^1.1.3

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - lib/Assets/IconApp/
    - lib/Assets/Images/
    - lib/Assets/Svg/

flutter_intl:
  enabled: true
